[colors.primary]
background = '#131318'
foreground = '#e4e1e8'

[colors.cursor]
text = '#131318'
cursor = '#e4e1e8'

[colors.vi_mode_cursor]
text = '#131318'
cursor = '#cacdff'

[colors.search.matches]
foreground = '#464651'
background = '#ffbcef'

[colors.search.focused_match]
foreground = '#464651'
background = '#cacdff'

[colors.footer_bar]
foreground = '#464651'
background = '#e4e1e8'

[colors.hints.start]
foreground = '#464651'
background = '#c2c4e7'

[colors.hints.end]
foreground = '#464651'
background = '#c2c4e7'

[colors.selection]
text = '#c7c5d2'
background = '#464651'


[colors.normal]
black   = '#464651'
red     = '#ffb4ab'
green   = '#cacdff'
yellow  = '#c2c4e7'
blue    = '#ffbcef'
magenta = '#bdc2ff'
cyan    = '#c2c4e7'
white   = '#e4e1e8'


[colors.bright]
black   = '#908f9c'
red     = '#ffb4ab'
green   = '#cacdff'
yellow  = '#c2c4e7'
blue    = '#ffbcef'
magenta = '#bdc2ff'
cyan    = '#c2c4e7'
white   = '#e4e1e8'


[colors.dim]
black   = '#464651'
red     = '#ffb4ab'
green   = '#cacdff'
yellow  = '#c2c4e7'
blue    = '#ffbcef'
magenta = '#bdc2ff'
cyan    = '#c2c4e7'
white   = '#e4e1e8'
